dist: trusty
sudo: true

language: python
python:
- '3.6'
env:
  global:
  - GETH_URL_LINUX='https://gethstore.blob.core.windows.net/builds/geth-linux-amd64-1.8.0-5f540757.tar.gz'
  - GETH_URL_MACOS='https://gethstore.blob.core.windows.net/builds/geth-darwin-amd64-1.8.0-5f540757.tar.gz'
  - GETH_VERSION='1.8.0'
  - SOLC_URL_LINUX='https://github.com/ethereum/solidity/releases/download/v0.4.23/solc-static-linux'
  - SOLC_URL_MACOS='https://www.dropbox.com/s/4amq3on2ds1dq36/solc_0.4.23?dl=0'
  - SOLC_VERSION='v0.4.23'
  - SYNAPSE_URL='https://github.com/matrix-org/synapse/tarball/master#egg=synapse'
  - SYNAPSE_SERVER_NAME='matrix.local.raiden'
  matrix:
  - TEST='./raiden/tests/unit'
  - TEST='./raiden/tests/integration --ignore=./raiden/tests/integration/transfer --ignore=./raiden/tests/integration/long_running --ignore=./raiden/tests/integration/api --ignore=.raiden/tests/integration/contracts' TRANSPORT_OPTIONS='--transport=udp'
  #- TEST='./raiden/tests/integration --ignore=./raiden/tests/integration/transfer --ignore=./raiden/tests/integration/long_running --ignore=./raiden/tests/integration/api --ignore=.raiden/tests/integration/contracts' TRANSPORT_OPTIONS='--transport=matrix --local-matrix=${HOME}/.bin/run_synapse.sh' RUN_SYNAPSE=1
  - TEST='./raiden/tests/integration/transfer' TRANSPORT_OPTIONS='--transport=udp'
  #- TEST='./raiden/tests/integration/transfer' TRANSPORT_OPTIONS='--transport=matrix --local-matrix=${HOME}/.bin/run_synapse.sh' RUN_SYNAPSE=1
  - TEST='./raiden/tests/integration/long_running ./raiden/tests/integration/contracts'
  - TEST='./raiden/tests/integration/api' TRANSPORT_OPTIONS='--transport=udp'
  #- TEST='./raiden/tests/integration/api' TRANSPORT_OPTIONS='--transport=matrix --local-matrix=${HOME}/.bin/run_synapse.sh' RUN_SYNAPSE=1
cache:
  pip: true
  directories:
  - "$HOME/.cache/pip"
  - "$HOME/.ethash"
  - "$HOME/.bin"
before_install:
  - mkdir -p $HOME/.bin
  - export PATH=$PATH:$HOME/.bin
  - ./.travis/before_install.sh
install:
  ./.travis/install.sh
before_script:
  ./.travis/before_script.sh
script:
  - ./.travis/run.sh
after_script:
  - coveralls
notifications:
  webhooks:
  - secure: IXBsyQtH29Vkh+Pe2exrbE3L8FJMQFqJ8ZRxkACts7cQtB8Iz1vyjWg9nYE9ZuCj/JWEeMZd/09JvwwKUj8ZEzwj59gFwVQFwTAxJbiDLRsn7WpdI5Q2fQ9ZPZIAbPo/mJejeHC+z3d5UgY72hbhqWuPJAa4ApWWKE5mPFUIr9uxgs01ReWs/y5HaPawQkSQAKVWWsS5R52Oyr9CYQNbfqfWcoLvzdiIZpsBi2r4ZK3NGrBZPGo4b+PkDkWjuBhMJ0FVABFCJT/bT2ORFsmsCDwZ4I3vOrKtJGDybmwONZqr0ymfYo1lbcUp0mE0zJ0ApyRtLqEFiTzaQqenlAZmBAtpDZVvpxFuDwZgFxafpNutO3Aj3Xbfe+aaooPfHA7SoxmxG/3gWY+OyaME8EDePfBHM0c1gGsNHmbPLt8k0lmwYKlNTFtFFyRAbL3700j19utkGroOK6CUYbed9YD96UehQTj7HN8rpLTZzSMh39c1JHVyqxsUZKkhQgY4GPgx2RAIiCVrwc6wN3Ebtwft0hA2UhvDodsc/qBAyz/YnSp2oKZKagLy5747torZybtNOGKCaV2fT3mSTxV2UNwPJ/N94dlTquJNx3StHT0IqD3Kfo5HYKJKHeri6lttTDul3rjAs1xxB2aAMutsyg7dRbBMmuKlK9gAtoS3UKthQdk=
stages:
  - lint
  - test
  - deploy
jobs:
  include:
    - stage: lint
      sudo: false
      before_install: /bin/true
      install: pip install -r requirements-lint.txt
      before_script: /bin/true
      script: make lint
      after_script: /bin/true
      env: LINT=1 TEST=""
    - stage: deploy
      if: tag IS present
      before_install: mkdir -p $HOME/.bin; export PATH=$PATH:$HOME/.bin; ./.travis/before_install.sh
      install: ./.travis/install.sh
      before_script: ./.travis/before_script.sh
      script: RAIDENVERSION=$TRAVIS_TAG make bundle-docker
      env: TEST=""
      deploy:
      - provider: releases
        api_key:
          secure: O85yltVQ1OacJQoNQWDJqOsXuSb+x7IMJTtUPuFM5iAOIGLmzhk0/qzJInixCGbAfWMYT4wTjA6OfxeiAWYzC5pCgqedZOsjp+8bXjn2Ek443Y+FBay3g38ebn3KBFBat3iMOamdrFSGTENugdG418GdK6yFVYpyCCUJXWLBcBUPOi7BlakI8TkznsaCad7OVRrPfMHWRe11WI3b4fajPnH/M7JRdDpT5GTisEchwKzYHnBttYySDZcQS3gtAEK7Srg9AkdEYCW3DOkmW4DeEgrQAQVcHHAV7eZREC1M3SrsrCotEqhEmIy29akOVKpOZtYWMxNFIsScDt39Y2hJLXRo1NjN0RBgIOg+Asl3B1cuK3Zfzc30r+Fyfkl9yFXpC35xddh2dHz5PFyssmtVZMEdxECtQT0DN08FB1JNdBbz3tfNw84IvR2ymYcQdRFWQM51rBUjUGspzDftAdITKkk3Z67jgYnaVvL0iBMbuuFjZDs8375IjIo7hxJ5UY7YWLV8Ic2r89wq5Dw7EsL5cyc4BVfj1kByZ1BJ6sZEKaqVdDdEc1Bv2/SYk6Da/muPB9gYK8Baw1gumLvrVS65EUVvwGmnq0zKrKmvTLl0aNPRNInaOVOloK63HdOwJhiLRn50YfCARrX+5kKBIQxdtNtmfPmdYJ3cm5bNhaXQ8fs=
        file: dist/raiden-${TRAVIS_TAG}-linux.tar.gz
        skip_cleanup: true
        on:
          tags: true
          repo: raiden-network/raiden
          branch: master
      - provider: pypi
        user: raiden_pypi_automated
        password:
            secure: pGSz00xatE6rLdmEvyHW2wM6VJvDeTY8s/huZzPLdAxX30UHZZACugdDNBCYgLmBpKN4pRrw5hXZ+09/6+MUpXHwFZ7tExJftUkHdLt9kY6bD/orFeHLU0hGzXJHSvCmGv2sTJ018j6MoKPiF+AzLaqExbHoOJZxtOf3O9a5LjP7M0uMDmUuCkBu2Y59Ozf3K5/uHio4pFDKTVg/jT5UzQ183LDvSPyfm/n0vbpvGyhfkThE+Nyk2Qs9Lu6WJjWj/Z96TZmnfqTfk9HIzePbkQSc1GLW2emCCYg5J8sGhKKShZ+1fGdhzN2nZQ2ccqnpLn+VJOumBQC+7fNlk7iKGBf10kESNlua/ccmD/jksdvYPlRQe12M0MqMh3cLRZU5EzEBMh/eIjQKj3MMPCk+YtSbXn6dITvZD/tkLXwQljNXHZvj4JEfdkP2dxORhMJ+TFwmvMgWyKhoSKTrZnN17qK2X9Agsr3taJ6RyzBMSzXDeSglNoYh/0mChLARjIXyz3WcoiIzpaRL8wPot1aRe4np/Rg+6c6PLMNvIAjgvNAvRFHCwKWzYwFaHjmi7bgDS6dirWdFd+TjAXCb8HFq+m670a0GY7u5JgHrU30QcfbeXhFJBUaBFkvDpJw53JogURlL+Et9So5xcJjYsYocUtrZi6YZ58UUu8A7ZWF0DNk=
        python: 3.6
        on:
          tags: true
          distributions: sdist bdist_wheel
          repo: raiden-network/raiden
          branch: master
    - stage: deploy
      if: tag IS present
      os: osx
      language: generic
      osx_image: xcode8.3
      env: TEST=""
      before_install:
        - sysctl -n machdep.cpu.brand_string
        - mkdir -p $HOME/.bin
        - export PATH=$HOME/.bin:$HOME/Library/Python/3.6/bin:/usr/local/bin/:$PATH
        - .travis/before_install.sh
      install:
        - .travis/install.sh
      before_script:
        - .travis/before_script.sh
        - python setup.py build
        - python setup.py compile_webui
      after_script:
        - .travis/update_formula.sh
      script:
        # pdbpp interferes with pyinstaller, uninstall it
        - pip uninstall -y pdbpp
        - pyinstaller --noconfirm --clean raiden.spec
        - cd dist && zip -9 -r raiden-${TRAVIS_TAG}-macOS.zip raiden*
      deploy:
        - provider: releases
          api_key:
            secure: O85yltVQ1OacJQoNQWDJqOsXuSb+x7IMJTtUPuFM5iAOIGLmzhk0/qzJInixCGbAfWMYT4wTjA6OfxeiAWYzC5pCgqedZOsjp+8bXjn2Ek443Y+FBay3g38ebn3KBFBat3iMOamdrFSGTENugdG418GdK6yFVYpyCCUJXWLBcBUPOi7BlakI8TkznsaCad7OVRrPfMHWRe11WI3b4fajPnH/M7JRdDpT5GTisEchwKzYHnBttYySDZcQS3gtAEK7Srg9AkdEYCW3DOkmW4DeEgrQAQVcHHAV7eZREC1M3SrsrCotEqhEmIy29akOVKpOZtYWMxNFIsScDt39Y2hJLXRo1NjN0RBgIOg+Asl3B1cuK3Zfzc30r+Fyfkl9yFXpC35xddh2dHz5PFyssmtVZMEdxECtQT0DN08FB1JNdBbz3tfNw84IvR2ymYcQdRFWQM51rBUjUGspzDftAdITKkk3Z67jgYnaVvL0iBMbuuFjZDs8375IjIo7hxJ5UY7YWLV8Ic2r89wq5Dw7EsL5cyc4BVfj1kByZ1BJ6sZEKaqVdDdEc1Bv2/SYk6Da/muPB9gYK8Baw1gumLvrVS65EUVvwGmnq0zKrKmvTLl0aNPRNInaOVOloK63HdOwJhiLRn50YfCARrX+5kKBIQxdtNtmfPmdYJ3cm5bNhaXQ8fs=
          file: dist/raiden-${TRAVIS_TAG}-macOS.zip
          skip_cleanup: true
          on:
            tags: true
            repo: raiden-network/raiden
            branch: master
