- name: Raiden docker container
  docker_container:
    name: raiden
    state: started
    restart_policy: always
    pull: yes
    image: "{{ docker_repo_raiden }}"
    etc_hosts:
      logstash: "{{ hostvars[groups['role_infrastructure'][0]]['private_ip'] }}"
    hostname: "{{ hostname }}"
    ports:
      - 38647:38647/udp
      - 5001:5001
    volumes:
      - "{{ raiden_root }}:/root/.raiden"
      - "{{ keystore_root }}:/keystore"
    env:
      RAIDEN_LOGSTASH_HOST: logstash
    command:
      - "--eth-nodes"
      - "{% for item in groups['role_eth'] %}{{ hostvars[item]['private_ip'] }}{{ '' if loop.last else ',' }}{% endfor %}"
      - "--seed"
      - "{{ private_ip }}"
      - "--raiden-executable"
      - "{{ 'raiden_echo_node' if hostvars[inventory_hostname].get('tags.Echo') == 'true' else 'raiden' }}"
      - "--"
      - "--api-address"
      - "0.0.0.0:5001"
      - "--keystore-path"
      - "/keystore"
      - "--address"
      - "{{ keystore_address }}"
      - "--password-file"
      - "/keystore/password"
      - "--logging"
      - ":trace"
      - "--log-json"
      - "{{ '--token-address' if hostvars[inventory_hostname].get('tags.Echo') == 'true' else '' }}"
      - "{{ echo_node_token_address if hostvars[inventory_hostname].get('tags.Echo') == 'true' else '' }}"
